# Generated by Django 6.1.1 on 2026-09-21 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up_at', models.DateTimeField(db_index=True)),
                ('purpose', models.CharField(choices=[('Phone Call', 'Phone Call'), ('WhatsApp', 'WhatsApp'), ('Meeting', 'Meeting'), ('Demo', 'Demo'), ('Email', 'Email'), ('Proposal', 'Proposal'), ('Payment Follow-up', 'Payment Follow-up'), ('Other', 'Other')], default='Phone Call', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('OVERDUE', 'Overdue')], db_index=True, default='PENDING', max_length=20)),
                ('outcome', models.TextField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='customers.customer')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='leads.lead')),
            ],
            options={
                'ordering': ['follow_up_at'],
                'indexes': [models.Index(fields=['status'], name='followups_f_status_257d35_idx'), models.Index(fields=['follow_up_at'], name='followups_f_follow__ec639d_idx'), models.Index(fields=['assigned_to'], name='followups_f_assigne_6dfa16_idx')],
            },
        ),
    ]
