# Generated by Django 6.1.1 on 2026-09-25 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followup',
            options={'ordering': ['-follow_up_at']},
        ),
        migrations.AddField(
            model_name='followup',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
