# Generated by Django 6.1.1 on 2026-09-25 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('LEAD_ASSIGNED', 'Lead Assigned'), ('LEAD_HANDED_OVER', 'Lead Handed Over'), ('LEAD_STAGE_CHANGED', 'Lead Stage Changed'), ('FOLLOW_UP_CREATED', 'Follow-up Created'), ('FOLLOW_UP_ASSIGNED', 'Follow-up Assigned'), ('FOLLOW_UP_DUE_SOON', 'Follow-up Due Soon'), ('FOLLOW_UP_OVERDUE', 'Follow-up Overdue'), ('FOLLOW_UP_COMPLETED', 'Follow-up Completed'), ('INTERNAL_MENTION', 'Internal Mention'), ('INTERNAL_COMMENT', 'Internal Team Comment'), ('CUSTOMER_CONVERTED', 'Customer Converted'), ('LEAD_UPDATED', 'Important Lead Update'), ('DUPLICATE_WARNING', 'Duplicate Lead Warning'), ('SYSTEM', 'System Notification')], db_index=True, default='SYSTEM', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('entity_type', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('entity_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('action_url', models.CharField(blank=True, max_length=255, null=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='NORMAL', max_length=20)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['recipient', 'created_at'], name='notificatio_recipie_f39341_idx'), models.Index(fields=['entity_type', 'entity_id'], name='notificatio_entity__950da6_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx')],
            },
        ),
    ]
