# Generated by Django 6.1.1 on 2026-09-21 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('LEAD', 'Lead'), ('CUSTOMER', 'Customer'), ('FOLLOW_UP', 'Follow Up'), ('USER', 'User')], db_index=True, max_length=50)),
                ('entity_id', models.CharField(db_index=True, max_length=64)),
                ('action', models.CharField(choices=[('LEAD_CREATED', 'Lead Created'), ('LEAD_UPDATED', 'Lead Updated'), ('STATUS_CHANGED', 'Status Changed'), ('LEAD_ASSIGNED', 'Lead Assigned'), ('LEAD_REASSIGNED', 'Lead Reassigned'), ('FOLLOW_UP_CREATED', 'Follow-up Created'), ('FOLLOW_UP_UPDATED', 'Follow-up Updated'), ('FOLLOW_UP_COMPLETED', 'Follow-up Completed'), ('FOLLOW_UP_CANCELLED', 'Follow-up Cancelled'), ('NOTE_ADDED', 'Note Added'), ('LEAD_CONVERTED', 'Lead Converted to Customer'), ('LEAD_MARKED_LOST', 'Lead Marked Lost'), ('CUSTOMER_CREATED', 'Customer Created'), ('CUSTOMER_UPDATED', 'Customer Updated')], db_index=True, max_length=50)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='activity_ac_entity__564be5_idx'), models.Index(fields=['created_at'], name='activity_ac_created_a8727e_idx')],
            },
        ),
    ]
