# Generated by Django 6.1.1 on 2026-09-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('LEAD_CREATED', 'Lead Created'), ('LEAD_UPDATED', 'Lead Updated'), ('STATUS_CHANGED', 'Status Changed'), ('LEAD_ASSIGNED', 'Lead Assigned'), ('LEAD_REASSIGNED', 'Lead Reassigned'), ('FOLLOW_UP_CREATED', 'Follow-up Created'), ('FOLLOW_UP_UPDATED', 'Follow-up Updated'), ('FOLLOW_UP_COMPLETED', 'Follow-up Completed'), ('FOLLOW_UP_CANCELLED', 'Follow-up Cancelled'), ('NOTE_ADDED', 'Note Added'), ('LEAD_CONVERTED', 'Lead Converted to Customer'), ('LEAD_MARKED_LOST', 'Lead Marked Lost'), ('CUSTOMER_CREATED', 'Customer Created'), ('CUSTOMER_UPDATED', 'Customer Updated'), ('CALL_LOGGED', 'Call Logged')], db_index=True, max_length=50),
        ),
    ]
