# Generated by Django 6.0.5 on 2026-10-05 05:59

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0006_lead_icp_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ICPScoringConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poor_fit_max', models.PositiveIntegerField(default=39)),
                ('potential_fit_max', models.PositiveIntegerField(default=59)),
                ('good_fit_max', models.PositiveIntegerField(default=79)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ICP Scoring Config',
                'verbose_name_plural': 'ICP Scoring Config',
            },
        ),
        migrations.CreateModel(
            name='ICPQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.PositiveIntegerField(default=0)),
                ('max_score', models.PositiveIntegerField(default=0)),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('icp_status', models.CharField(choices=[('POOR_FIT', 'Poor Fit'), ('POTENTIAL_FIT', 'Potential Fit'), ('GOOD_FIT', 'Good Fit'), ('STRONG_ICP_FIT', 'Strong ICP Fit')], db_index=True, max_length=20)),
                ('thresholds_snapshot', models.JSONField(blank=True, default=dict)),
                ('qualified_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icp_qualifications', to='leads.lead')),
                ('qualified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='icp_qualifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ICP Qualification',
                'verbose_name_plural': 'ICP Qualifications',
                'ordering': ['-qualified_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ICPQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, help_text='Optional help text shown under the question.', null=True)),
                ('question_type', models.CharField(choices=[('SINGLE_CHOICE', 'Single Choice'), ('MULTI_CHOICE', 'Multiple Choice'), ('YES_NO', 'Yes / No'), ('NUMBER', 'Number'), ('TEXT', 'Text'), ('DROPDOWN', 'Dropdown')], db_index=True, default='SINGLE_CHOICE', max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=1)),
                ('max_points', models.PositiveIntegerField(default=0, help_text='Maximum points for this question. Auto-derived for choice and number questions, configured manually for text questions.')),
                ('scoring_rules', models.JSONField(blank=True, default=list, help_text='Number questions only. Ordered list of {"min": number, "max": number, "points": number}. The first matching range wins.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='icp_questions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ICP Question',
                'verbose_name_plural': 'ICP Questions',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ICPQualificationAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_snapshot', models.JSONField(blank=True, default=dict)),
                ('answer_value', models.TextField(blank=True, default='')),
                ('selected_options', models.JSONField(blank=True, default=list, help_text='Choice questions only. Frozen list of {"id", "text", "points"}.')),
                ('points_earned', models.PositiveIntegerField(default=0)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='icp.icpqualification')),
                ('question', models.ForeignKey(blank=True, help_text='Kept for reference only. Snapshots guarantee historical results never change.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualification_answers', to='icp.icpquestion')),
            ],
            options={
                'verbose_name': 'ICP Qualification Answer',
                'verbose_name_plural': 'ICP Qualification Answers',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ICPQuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=200)),
                ('points', models.PositiveIntegerField(default=0)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='icp.icpquestion')),
            ],
            options={
                'verbose_name': 'ICP Question Option',
                'verbose_name_plural': 'ICP Question Options',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
