# Generated by Django 6.1.1 on 2026-09-27 18:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0005_commentmention_internalcomment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_type', models.CharField(choices=[('Outbound', 'Outbound'), ('Inbound', 'Inbound')], default='Outbound', max_length=20)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='calls/audio/%Y/%m/')),
                ('transcript', models.TextField(blank=True, default='')),
                ('ai_summary', models.TextField(blank=True, default='')),
                ('key_points', models.JSONField(blank=True, default=list)),
                ('customer_requirements', models.JSONField(blank=True, default=list)),
                ('objections', models.JSONField(blank=True, default=list)),
                ('customer_intent', models.CharField(blank=True, default='', max_length=100)),
                ('next_action', models.TextField(blank=True, default='')),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_calls', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='leads.lead')),
            ],
            options={
                'ordering': ['-started_at', '-created_at'],
                'indexes': [models.Index(fields=['lead', '-started_at'], name='ai_call_lead_id_88b7f7_idx'), models.Index(fields=['created_by', '-started_at'], name='ai_call_created_3a6c06_idx')],
            },
        ),
    ]
