# Generated by Django 6.1.1 on 2026-09-28 06:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        ('leads', '0005_commentmention_internalcomment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='ai_model',
            field=models.CharField(blank=True, default='gemini-2.5-flash', max_length=100),
        ),
        migrations.AddField(
            model_name='call',
            name='ai_provider',
            field=models.CharField(blank=True, default='gemini', max_length=50),
        ),
        migrations.AddField(
            model_name='call',
            name='processing_status',
            field=models.CharField(choices=[('UPLOADING', 'Uploading'), ('TRANSCRIBING', 'Transcribing'), ('ANALYZING', 'Analyzing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='COMPLETED', max_length=20),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['processing_status'], name='ai_call_process_855d70_idx'),
        ),
    ]
