# Generated by Django 6.0.5 on 2026-09-25 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='#6366F1', max_length=30)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lead Stage',
                'verbose_name_plural': 'Lead Stages',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='LeadHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handed_over_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers_performed', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers', to='leads.lead')),
                ('new_assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handovers_to', to=settings.AUTH_USER_MODEL)),
                ('previous_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers_from', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead Handover',
                'verbose_name_plural': 'Lead Handovers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='leads.leadstage'),
        ),
    ]
