# Generated by Django 6.0.5 on 2026-10-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_commentmention_internalcomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='icp_status',
            field=models.CharField(choices=[('NOT_TESTED', 'Not Tested'), ('POOR_FIT', 'Poor Fit'), ('POTENTIAL_FIT', 'Potential Fit'), ('GOOD_FIT', 'Good Fit'), ('STRONG_ICP_FIT', 'Strong ICP Fit')], db_index=True, default='NOT_TESTED', max_length=20),
        ),
    ]
