# Generated by Django 6.0.5 on 2026-10-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_lead_icp_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='pld_score',
            field=models.PositiveIntegerField(default=0, help_text='Points earned by the most recent PLD assessment.'),
        ),
        migrations.AddField(
            model_name='lead',
            name='pld_status',
            field=models.CharField(choices=[('NOT_ASSESSED', 'Not Assessed'), ('UNQUALIFIED', 'Unqualified'), ('QUALIFIED_PLD', 'Qualified PLD')], db_index=True, default='NOT_ASSESSED', max_length=20),
        ),
    ]
