# Generated by Django 6.0.5 on 2026-10-05 08:09

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0007_lead_pld_score_lead_pld_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PLDScoringConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualified_min_percentage', models.PositiveIntegerField(default=60, help_text='Minimum percentage of the active problem pool needed to qualify.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PLD Scoring Config',
                'verbose_name_plural': 'PLD Scoring Config',
            },
        ),
        migrations.CreateModel(
            name='PLDAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.PositiveIntegerField(default=0)),
                ('max_score', models.PositiveIntegerField(default=0)),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('pld_status', models.CharField(choices=[('UNQUALIFIED', 'Unqualified'), ('QUALIFIED_PLD', 'Qualified PLD')], db_index=True, max_length=20)),
                ('problems_snapshot', models.JSONField(blank=True, default=list)),
                ('config_snapshot', models.JSONField(blank=True, default=dict)),
                ('assessed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pld_assessments', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pld_assessments', to='leads.lead')),
            ],
            options={
                'verbose_name': 'PLD Assessment',
                'verbose_name_plural': 'PLD Assessments',
                'ordering': ['-assessed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PLDProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('points', models.PositiveIntegerField(default=10, help_text='Points awarded when this problem is selected for a lead.')),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='MEDIUM', max_length=12)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pld_problems_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PLD Problem',
                'verbose_name_plural': 'PLD Problems',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PLDAssessmentProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_snapshot', models.JSONField(blank=True, default=dict)),
                ('points_earned', models.PositiveIntegerField(default=0)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='pld.pldassessment')),
                ('problem', models.ForeignKey(blank=True, help_text='Kept for reference only. Snapshots guarantee historical results never change.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_problems', to='pld.pldproblem')),
            ],
            options={
                'verbose_name': 'PLD Assessment Problem',
                'verbose_name_plural': 'PLD Assessment Problems',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PLDStageGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_icp_min_status', models.CharField(blank=True, choices=[('POOR_FIT', 'Poor Fit'), ('POTENTIAL_FIT', 'Potential Fit'), ('GOOD_FIT', 'Good Fit'), ('STRONG_ICP_FIT', 'Strong ICP Fit')], default='', help_text='Leave blank to skip the ICP fit requirement.', max_length=20)),
                ('require_pld_qualified', models.BooleanField(default=False, help_text='Require the lead to hold the Qualified PLD status.')),
                ('require_problems_assessed', models.BooleanField(default=False, help_text='Require at least one completed PLD assessment on the lead.')),
                ('notes', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pld_gate', to='leads.leadstage')),
            ],
            options={
                'verbose_name': 'PLD Stage Gate',
                'verbose_name_plural': 'PLD Stage Gates',
                'ordering': ['stage__display_order', 'stage__id'],
            },
        ),
    ]
