# Generated by Django 6.0.5 on 2026-10-08 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_lead_pld_score_lead_pld_status'),
        ('pld', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pldassessment',
            name='stage',
            field=models.ForeignKey(blank=True, help_text='The pipeline stage this assessment was completed for.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pld_assessments', to='leads.leadstage'),
        ),
        migrations.AddField(
            model_name='pldproblem',
            name='stage',
            field=models.ForeignKey(blank=True, help_text='Stage this problem/question belongs to. Blank applies globally or when stage has no specific questions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pld_problems', to='leads.leadstage'),
        ),
        migrations.AddField(
            model_name='pldstagegate',
            name='qualified_min_percentage',
            field=models.PositiveIntegerField(blank=True, help_text='Optional stage-specific percentage threshold. If blank, uses global scoring config.', null=True),
        ),
        migrations.AlterField(
            model_name='pldproblem',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pldstagegate',
            name='require_pld_qualified',
            field=models.BooleanField(default=False, help_text='Require the lead to hold the Qualified PLD status for this stage.'),
        ),
        migrations.AlterField(
            model_name='pldstagegate',
            name='require_problems_assessed',
            field=models.BooleanField(default=False, help_text='Require a completed PLD assessment for this stage.'),
        ),
    ]
